### ISSUE TITLE
Change return value of `getRootElement()` from element with specific id to `document.body` element

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#1042]
### Description

`getRootElement()` 함수의 반환값을 특정 id를 가진 엘리먼트(e.g. `main`)에서 `document.body` 엘리먼트로 변경합니다.

### Reasons for suggestion

1. 범용적이지 않습니다. `main` 이라는 id는 채널의 데스크 어플리케이션에서 주입한 값이기 때문에, 다른 애플리케이션에서 라이브러리를 사용하려면 최상위 엘리먼트의 id를 `main` 으로 사용처에서 명시해주어야합니다. 추가로, `root` id를 가진 엘리먼트는 스토리북의 루트 엘리먼트입니다. 라이브러리 함수의 구현이 특정한 어플리케이션/라이브러리의 구현에 기대고 있는 상황입니다.
2. `getRootElement()` 함수는 `Modal`, `Overlay` 등 Floating UI에서 사용하고 있습니다. 해당 UI들이 다른 엘리먼트보다 높이 쌓이려면, 어플리케이션의 루트의 자식 엘리먼트가 아닌, 형제 엘리먼트에 렌더되는 게 관리하기에 간편합니다. 어플리케이션 내부의 쌓임 맥락에 관계 없이 어플리케이션 루트 엘리먼트 하나와의 우선 순위만 관리하면 되기 때문입니다.

### Proposed solution

```tsx
/* AS-IS */
export const getRootElement = () =>
  document.getElementById!('main') ||
  document.getElementById!('root') ||
  document.getElementById!('__next') as HTMLElement

/* TO-BE */
export const getRootElement = () => document.body
```

- 변경 외에도, 어플리케이션에서 문제가 없는지 로컬 빌드 후 테스트가 필요합니다.
- 후속 작업으로 불필요한 z-index를 제거해야합니다.

**Comment by inhibitor1217** [comment]
Also see #773
