### ISSUE TITLE
Fix default value of `ListItem` size prop

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#1117]
### Summary

현재 `ListItem` 의 size prop의 default value 가 `ListItemSize.M` 으로 지정되어있습니다.

### Reproduction process

<img width="685" alt="image" src="https://user-images.githubusercontent.com/28595102/215921026-40b5a92b-9c44-499f-8fc5-23a32afd9c4c.png">

실제 스펙을 보면 `ListItemSize.S` 가 default value 이기 때문에 변경이 필요합니다. `ListItemSize.S` 는 `padding: 4px 6px` 인 반면 `ListItemSize.M` 은 `padding: 6px` 이기 때문에 차이가 생깁니다.

디자인상으로 `ListItemSize.M`을 사용하고 있어서 size prop를 default value 로 지정하고 있는 곳이 있을 수 있기 때문에 주의해야 합니다.

### Version of bezier-react

@1.0.0-next-v1.180

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by yangwooseong** [comment]
(https://github.com/channel-io/bezier-react/pull/1621#issuecomment-1724872592)

베지어 스펙과 구현상 차이가 있어서 발생하는 문제. 베지어 스펙에 맞게 `ListItem` 컴포넌트의 속성을 하나씩 낮출(`L` -> `M`, `M` -> `S`, ...) 필요가 있습니다.

![image](https://github.com/channel-io/bezier-react/assets/28595102/6636300c-869f-45b5-b93f-b5f6a48f9a17)

https://next-v1--62bead1508281287d3c94d25.chromatic.com/?path=/story/components-listitem--primary&args=size:s;description:

**Comment by sungik-choi** [comment]
우선은 이 방향으로 유지하고, 다음 메이저 버전에서 수정하시죠
