### ISSUE TITLE
Remove default value of event handler props

### ISSUE THREAD

**Issue by heech1013** [channel-io/bezier-react#1123]
### Summary

각 컴포넌트의 이벤트 핸들러 props에 불필요하게 할당하고 있는 default value를 제거합니다.

### Reproduction process

컴포넌트의 이벤트 핸들러 props에 default value로 `noop`(`() => {}`)을 할당하는 경우, 특정 환경에서 버그가 발생할 수 있습니다.
- 예를 들어, [`Icon` 컴포넌트의 `onClick` prop에 default value가 할당됨으로 인해 상위 컴포넌트인 a 태그의 `tel:` link가 동작하지 않는 문제](https://github.com/channel-io/bezier-react/pull/1122)가 있습니다.

컴포넌트의 이벤트 핸들러에 default value를 할당하는 이유는 아래 정도로 파악하고 있습니다.
- 해당 prop의 값이 언제나 존재하도록 함으로써, 컴포넌트 내부 로직에서 optional chaining 등 값이 존재하지 않을 때의 상황을 대응하는 수고를 줄이기 위함.
- 별도로 정한 룰이나 이유는 없지만, 다른 베지어 컴포넌트에서 흔히 사용하는 방식을 따라간 경우

default value 할당을 제거함으로써 크게 불편해지거나 사이드 이펙트가 많이 발생하지는 않을 것으로 보입니다.
#1122 를 포함하여, 앞으로 발생할 수 있는 예상치 못한 버그를 방지하기 위해 점진적으로 default value 할당을 제거해나갈 것을 제안합니다.

### Version of bezier-react

@1.0.0-next-v1.180

### Browser

iPad Chrome browser app, etc.

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by sungik-choi** [comment]
v2.0.0에서 해결됨
