### ISSUE TITLE
Icon에 hoverColor 추가

### ISSUE THREAD

**Issue by aooen** [channel-io/bezier-react#118]
## 현재 상황
사용처에서 Icon에 따로 hover시 color를 지정해주는 경우가 많음

## 문제점
추후 다크모드 적용시 Icon별 hover style이 있는지 확인하여 지정해줘야 하는 문제가 있어서 복잡함

## 어떻게 개선할 수 있는지
Icon에 hoverColor 추가

# Reference

**Comment by sungik-choi** [comment]
`Icon` 컴포넌트가 독립적으로 hover 색상을 가져야하는지에 대해선 논의가 필요하다고 생각합니다. 보통 Icon을 감싸고 있는 상위 컴포넌트가 hover 되었을 때 하위 Icon 색상이 변경되는 경우가 많은데, 이 경우 Icon의 hover 색상은 상위 컴포넌트에서 관리해주어야 합니다.
