### ISSUE TITLE
React.Children.map for Fragment cause unexpected behaviour

### ISSUE THREAD

**Issue by Kanary159357** [channel-io/bezier-react#1222]
### Summary

`React.Children.map` for Fragment cause unexpected behaviour

### Reproduction process

https://github.com/channel-io/bezier-react/blob/985c935f70c6343a43404b0da1a967fdaf153f60/packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx#L50

`...Group`의 경우에 React.Children.map(children, (child, index) => ( )을 통해 하위의 `Children`들을 순회하는데, 
Children으로 Fragment로 한번 감싸고, 이 안에 실제 사용할 Children이 있는 경우에 의도대로 UI가 그려지지 않습니다. (Children인 Fragment를 순회하기 떄문)

예시 코드
```javascript
              <FormGroup spacing={16}>
                { formik.values.labelButton && (
                <>
                  <LabelButtonTextField
                    path="labelButtonText"
                    currentI18n={currentI18n}
                    onChange={handleChangeLabelButtonText}
                    onFocus={hadleFocusLabelButtonText}
                  />
                  <LabelButtonTextI18nForm
                    i18nMap={plugin.labelButtonTextI18nMap}
                    currentI18n={currentI18n}
                    setLauncherPreviewType={setLauncherPreviewType}
                    onChangeCurrentI18n={onChangeCurrentI18n}
                  />
                </>
                ) }
```

이는 [의도된 사항](https://github.com/facebook/react/issues/11859)이며 children의 요소가 Fragment인 경우에 Fragment의 첫번쨰 children을 순회하도록 하여 수정할 수 있습니다.

### Version of bezier-react

1.0.0-next-v1.189

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by sungik-choi** [comment]
위 레퍼런스처럼 `AlphaStack` 같은 컴포넌트를 별도로 만들어서, 내부의 `**Group` 의 구현에 적용해보는 것도 괜찮을 거 같아요!

**Comment by Kanary159357** [comment]
> * https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/AlphaStack/AlphaStack.tsx

좋은거 같습니다!
