### ISSUE TITLE
Add `forwardRef` to `Icon`

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#1313]
### Description

현재 아이콘 컴포넌트의 DOM node에 접근할 수 없습니다.

### Reasons for suggestion

- `ref` 를 `Icon` 인터페이스에서 제공하므로, 당연히 의도한대로 동작해야합니다.
- 대부분의 상황에선 문제가 없으나, radix-ui의 `Slot` (`asChild`) 속성과 아이콘을 함께 사용 시 테스트에서 에러 메세지가 출력됩니다.

### Considerations

- 인터페이스 변경에 따른 Breaking Change 고려 (Type declaration 충돌)
- 이 PR의 변경사항이 적용되는 bezier-icons의 버전을 bezie-react peer dependency로 업데이트해야 합니다.

**Comment by yangwooseong** [comment]
Icon 컴포넌트에 이미 ref forwarding 은 있는데 radix와 같이 사용하는 경우에만 문제가 되는 걸로 이해하면 될까요? 제목처럼 Add forwardRef to Icon 은 이미 되어있어서 질문드립니다

**Comment by sungik-choi** [comment]
> 그게 아니라 forwardRef 로 감쌌지만 icon 패키지에서 빌드된 컴포넌트에 forwarding이 안되고 있는 상태인 것인가요?

넵 맞아요. bezier-icons의 rollup config에서,

```ts
  /**
   * @type {import('@svgr/babel-plugin-transform-svg-component').Template}
   */
  function reactIconTemplate({ imports, componentName, props, jsx }, { tpl }) {
    return tpl`
      ${imports}

      import { createBezierIcon } from '${config.input.utils}'

      function ${componentName}(${props}) {
        return (
          ${jsx}
        )
      }

      export default createBezierIcon(${componentName})
    `
  }
```

위 템플릿을 변경해야해요.

**Comment by yangwooseong** [comment]
> 인터페이스 변경에 따른 Breaking Change 고려 (Type declaration 충돌)

템플릿 변경해서 build 하고 아이콘에 ref forwarding 전달 잘 되는 것은 확인했습니다. 그런데 IconSource 타입이 바뀌게 되서 말씀하신 것처럼 breaking change가 발생하는 게 약간 고민이네요. IconSource 타입 (혹은 BezierIcon 타입)을 `React.FunctionComponent<...>`으로 풀어서 쓰고 있는 사용처는 없는 것 같아서, patch 나 minor bump 로 해서 업데이트를 하는 것은 어떻게 생각하시나요? 

```tsx
As-is
export declare type IconSource = React.FunctionComponent<React.SVGProps<SVGSVGElement>>

To-be
export declare type IconSource = React.ForwardRefExoticComponent<React.SVGProps<SVGSVGElement> & React.RefAttributes<SVGSVGElement>>
```

**Comment by sungik-choi** [comment]
> > 인터페이스 변경에 따른 Breaking Change 고려 (Type declaration 충돌)
> 
> 템플릿 변경해서 build 하고 아이콘에 ref forwarding 전달 잘 되는 것은 확인했습니다. 그런데 IconSource 타입이 바뀌게 되서 말씀하신 것처럼 breaking change가 발생하는 게 약간 고민이네요.
> 
> 제 생각에는 IconSource 타입 (혹은 BezierIcon 타입)을 활용할때 기존의 타입처럼 `React.FunctionComponent<...>`으로 풀어서 쓰고 있는 사용처는 없는 것 같아서 실제로 breaking change가 발생하지는 않을 것 같아요. 그래서 메이저 버전업을 할 때 포함시키기보다는 patch 나 minor bump 로 해서 업데이트를 하는 것이 낫지 않나 싶네요. 어떻게 생각하시나요? @sungik-choi
> 
> ```tsx
> As-is
> export declare type IconSource = React.FunctionComponent<React.SVGProps<SVGSVGElement>>
> 
> To-be
> export declare type IconSource = React.ForwardRefExoticComponent<React.SVGProps<SVGSVGElement> & React.RefAttributes<SVGSVGElement>>
> ```

데스크에 우선 적용해보고 문제없다면 마이너로 배포하면 될 거 같습니다!
