### ISSUE TITLE
`SegmentedControl` Indicator's size is not updated correctly

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#1351]
### Summary

`SegmentedControl` Indicator's size is not updated correctly.

### Reproduction process

<img width="576" alt="image" src="https://github.com/channel-io/bezier-react/assets/58209009/cf47155b-0778-474d-bd4d-d0fbc66763d1">

- `Modal` 내부에 `SegmentedControl` 컴포넌트를 위치시켰을 때 발생합니다.
- 원인은 `Modal` 마운트 시 scale 트랜지션 + 리사이징 타이밍으로 보여집니다. 이후 옵션 변경 시에 리사이징은 잘 됩니다.
- 레거시 컴포넌트에선 발생하지 않았던 문제입니다.

### Version of bezier-react

1.0.0@next-v1.210

### Browser

113.0.5672.92(arm64)

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by yangwooseong** [comment]
이거 지금은 프로덕션에서 재현이 안되네요..!
