### ISSUE TITLE
Support `title`, `subtitle`, `closeIcon` in `ModalHeader` 

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#1457]
### Description

현재의 `ModalHeader`컴포넌트 interface 로는 디자인 요구사항이 변경되었을 때 대처하기가 어렵습니다.

 

### Reasons for suggestion

1. 모달외부를 클릭하더라도 모달이 닫히지 않게 하고 싶을 때가 있는데(e.g. 모달 내부에 복잡한 `form` 이 있을 경우), 이 경우는 헤더의 `hasCloseIcon` 가 `true`더라도 버튼의 `onHide` 핸들러가 동작하지 않습니다. 이럴 때는 사용처에서 `Button` 을 이용해서 직접 구현해아 하고, `title`역시 `Text` 로 직접 구현해야 합니다. 그러나 이런 구현 방식은 헤더의 스타일이 변경되었을 때 대처가 어려운 단점이 있습니다.

~~2. `title`과 `subtitle` 의 위치를 바꿔서 사용하고 싶을 때가 있습니다. 이 경우 역시 마찬가지로 직접 `Text`, `Stack` 등을 이용하여 구현해야 합니다.~~

2번은 논외로 하고 1번먼저 대응하는 것을 목표로 합니다. `closeOnBlur` 인터페이스를 모달에 (혹은 오버레이까지) 적용해야 합니다.

### Proposed solution

적어도 사용처에서 모달의 `title`, `subtitle`, `closeButton` 등을 import 하는 것을 허용하는 게 좋을 것 같습니다.

### References

없음

**Comment by sungik-choi** [comment]
- 1,2 모두 근본적으로 디자인 시스템의 모달 스펙이 명확하지 않아서 생기는 문제로 보입니다.
- 1번 안의 경우, 케이스가 많아서 `disableClickOutside` 같은 옵션을 추가하는 것도 괜찮다고 생각합니다.
- 2번 안의 경우 어렵네요. 이런 케이스까지 모두 고려하여 사용하기 쉬운 컴포넌트를 작성하긴 어려워보여서 꼭 이런 디자인(제목 역순)이 되어야만 하는지 먼저 커뮤니케이션해보는 게 좋을 거 같습니다.
