### ISSUE TITLE
Write wiki about how to update icons

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#1592]
## Summary

아이콘 업데이트 방식에 대한 개발자 위키 문서를 작성합니다.

## Details

[기존 Bezier Icons 소개 문서](https://github.com/channel-io/bezier-react/wiki/Introduction#bezier-icons)를 확장하면 좋겠습니다. 아래와 같은 내용들이 포함되면 좋겠습니다.

- 어떻게 아이콘이 업데이트되는지
- changeset 작성 방법, 컨벤션 및 향후 개선 계획

**Comment by sungik-choi** [comment]
@yangwooseong 같이 정리해보면 어떨까요?

**Comment by yangwooseong** [comment]
changeset 은 개발자가 직접 달고 있는 것이죠?

**Comment by sungik-choi** [comment]
> changeset 은 개발자가 직접 달고 있는 것이죠?

맞습니다
나중엔 체인지로그 생성도 자동화하는게 목표에요

**Comment by yangwooseong** [comment]
[위키 업데이트](https://github.com/channel-io/bezier-react/wiki/Introduction/_compare/c1f9089567da71268c3e519e1c8a988adb78a44d) 했습니다. 확인해주시고 추가할만 한 내용이 있으면 말씀해주세요~

**Comment by sungik-choi** [comment]
👍 좋습니다. 이슈는 닫을게요!
