### ISSUE TITLE
Write wiki about how to contribute to Bezier Figma Plugin

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#1593]
## Summary

베지어 피그마 플러그인 개발에 기여하는 방법에 대한 개발자 위키 문서를 작성합니다.

## Details

아래와 같은 내용들이 포함되면 좋겠습니다.

- 처음에 참고하기 좋은 피그마 공식 문서 링크
- 개발 및 테스트 방법
- 프로덕션(사내 클라우드) 배포 방법
- 디자이너와 커뮤니케이션하는 방법
- 앞으로 해볼 수 있는 것들 (variables to design token, codegen 등. 이슈 링크)

**Comment by sungik-choi** [comment]
@yangwooseong 같이 정리해보면 어떨까요?

**Comment by yangwooseong** [comment]
네 좋습니다! 플러그인 개발 작업이 어느정도 마무리 되는단계라 곧 시작해볼 수 있을 것 같아요 (#1592랑 같이)

**Comment by yangwooseong** [comment]
위키에 피그마 플러그인 관련 내용을 추가했습니다. 확인 부탁드려요 @sungik-choi

**Comment by sungik-choi** [comment]
💯 좋아요!
