### ISSUE TITLE
I would like to see a skeleton added.

### ISSUE THREAD

**Issue by wes5510** [channel-io/bezier-react#1629]
### Description

It would be great to have a skeleton UI for loading before displaying the content.

### Reasons for suggestion

This would provide a consistent UI representation and is commonly used.

### Proposed solution

It's not available yet...

### References

[Skeleton - Chakra UI](https://chakra-ui.com/docs/components/skeleton)

**Comment by leejiwoo2002** [comment]
Right now, Bezier only have [spinner component](https://github.com/channel-io/bezier-react/blob/main/packages/bezier-react/src/components/Spinner/Spinner.tsx)
<img width="364" alt="스크린샷 2023-09-14 오후 3 08 47" src="https://github.com/channel-io/bezier-react/assets/55074799/fd0a67bc-788f-425a-8b8c-8cd1eb4c0811">

**Comment by wes5510** [comment]
lol :)

**Comment by sungik-choi** [comment]
duplicate #1295
