### ISSUE TITLE
Wiriting code to convert dom utils(`getRootElement` ...) to `useWindow`

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#1817]
## Summary

- `getRootElement` 를 `useWindow` 로 변환하는 codemod 를 추가합니다.

## Description

- https://github.com/channel-io/bezier-react/pull/1764 에서 제시하듯이, 새로운 window 를 고려해야 하기 때문에 `getRootElement` 를 `useWindow`로 변환해야 합니다. 
- 대략적인 흐름을 생각해보면 다음과 같습니다.
1. getRootElement 를 사용하고 있는 최상위 함수를 찾는다.
2. `const window = useWindow()`를 함수 바로 밑에 선언하고 useWindow import 를 추가한다.
3. getRootElement() 를 window 로 대체하고 getRootElement import 를 제거한다.

```tsx
// As-is
import { getRootElement, Overlay } from '@channel.io/bezier-react'

function SomeOverlay() {
  return (
    <Overlay
      container={getRootElement()}
    />
  )
}

// To-be
import { useWindow, Overlay } from '@channel.io/bezier-react'

function SomeOverlay() {
  const window = useWindow()
  return (
    <Overlay
      container={window}
    />
  )
}
```

### References

- https://github.com/channel-io/bezier-react/pull/1764

**Comment by yangwooseong** [comment]
고민되는 점:
- getRootElement 의 사용처가 데스크 기준으로 13개밖에 없어서 오히려 codemod 만드는 비용이 더 클것으로 생각
- 특히 함수 prop 에 기본값으로 넘기는 경우 `const Component = ({ conatiner = getRootElement() }) => { ... }` 까지 자동화하려면 꽤 까다로워보임

codemod 를 쓰지 않는다면 베이저 사용처(프론트, 데스크, Document System, 등등) 마다 체크를 해야하는 번거로움은 있지만, 저희가 직접 해주는 것이 비용이 적어보이는데 어떻게 생각하시나요? @sungik-choi

**Comment by sungik-choi** [comment]
> codemod 를 쓰지 않는다면 베이저 사용처(프론트, 데스크, Document System, 등등) 마다 체크를 해야하는 번거로움은 있지만, 저희가 직접 해주는 것이 비용이 적어보이는데 어떻게 생각하시나요? @sungik-choi 

말씀주신대로 만들지 않는 것도 방법이에요. 마이그레이션 코드 구현 난이도가 높다면 마이그레이션 문서(changeset)에 잘 적어주는 것으로도 대체할 수 있을 거 같아요.

**Comment by yangwooseong** [comment]
넵 그럼 가이드에 적는 것으로 대체하시죠!
