### ISSUE TITLE
Drop `color`, `typo` props from `FormLabel`, `FormHelperText`, and `FormErrorMessage`

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#1902]
### Description

`FormLabel`, `FormHelperText`, `FormErrorMessage` 컴포넌트에서 다소 불필요하게 지원되는  `color`, `typo`속성을 제거합니다. 

### Reasons for suggestion

현재 두 컴포넌트 모두 고정된 스타일로 보여주고 있기 때문에 불필요하다고 판단됩니다. 

### Proposed solution

주 사용처인 데스크에서 사용되는 지 보고 없으면 지원 중단합니다. breaking change이기 때문에 메이저 버전을 올려야 합니다. 가능하면 메이저 버전 2로 올릴 때 제거하면 좋을 것 같습니다

### References

https://github.com/channel-io/bezier-react/pull/1893#issuecomment-1886403240

**Comment by sungik-choi** [comment]
@yangwooseong 이거 확인해주시면 좋을듯!

**Comment by yangwooseong** [comment]
확인해보니 FormHelperText, FormErrorMessage 단독으로 사용하는 경우 typo를 14로 사용하는 곳이 있어서 남겨둬도 괜찮겠다는 생각입니다
