### ISSUE TITLE
Rename `leftIcon` property of `NavItem` and `NavGroup` to `leftContent`

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#1929]
### Description

Rename `NavItem`'s `leftIcon` property to `leftContent`

### Reasons for suggestion

라이브러리 전반적으로 일관적인 인터페이스를 가지기 위한 변경입니다. leftContent의 타입을 BezierIcon으로 제한하여 Button등 다른 사이드 컨텐츠를 가진 컴포넌트의 사용 방식을 따르도록 하여, 사용자가 빠르게 학습할 수 있도록 합니다.

### Proposed solution

추가 마이그레이션 자동화 스크립트 지원이 필요할 수 있음.

**Comment by yangwooseong** [comment]
utils/component.ts 에 있는 함수를 약간 변형하면 금방 구현 가능해 보여서 스크립트 만들어보겠습니다!
