### ISSUE TITLE
IE 지원

### ISSUE THREAD

**Issue by jwoo0122** [channel-io/bezier-react#194]
## 어떻게 개선할 수 있는지

# Reference

**Comment by aooen** [comment]
근데 IE 곧 공식 지원 끝나는데 베지어가 지원해야 할 필요 있을까요?

**Comment by quino0627** [comment]
거진 1년 남았군요. 버텨 볼까요?
홈페이지에서 사용하고 싶어하시던데, 간단하게 원인을 찾아보는 것 정도 진행해볼 수 있겠네요

**Comment by sungik-choi** [comment]
2022/06/15 공식 IE11 지원 종료로 굳이 지원해야할 필요는 없을 거 같습니다. 
이슈 Close 하겠습니다!
