### ISSUE TITLE
Select components behave differently than before

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#2005]
### Summary

Select components behave differently than before

### Reproduction process

<img width="583" alt="Pasted image 20240220145702" src="https://github.com/channel-io/bezier-react/assets/58209009/da463425-61cf-4d99-ae7a-12c134a0f34b">

버전 적용 이후, 컨테이너에 의해 `overflow: hidden` 되는 경우가 있음.

### Version of bezier-react

2.0.0-alpha.12

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by yangwooseong** [comment]
어플리케이션에서 foundation 을 변환하는 과정에서 생긴 문제였습니다.
