### ISSUE TITLE
Fixed SectionLabel becoming a button element and behaving incorrectly

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#2007]
### Summary

Fixed SectionLabel becoming a button element and behaving incorrectly

### Reproduction process

<img width="726" alt="image" src="https://github.com/channel-io/bezier-react/assets/58209009/bb3fdb1e-f7c2-4df5-b75d-3cc8f6bbff9f">

- #1936 에서 SectionLabel이 button으로 동작할 수 있도록 변경했으나, 의도대로 사용되지 않는 케이스가 있는 거 같습니다.
- 의도한 동작이 이전과 다르므로(변경 안됨), 확인해봐야합니다.

### shrink

| AS-IS | TO-BE |
|:---:|:---:|
| <img width="301" alt="image" src="https://github.com/channel-io/bezier-react/assets/58209009/ae72688b-c1ee-48d2-9c7d-77fa5c3c9ac0"> | <img width="192" alt="image" src="https://github.com/channel-io/bezier-react/assets/58209009/15aa2999-e57f-4c2f-b565-1de90ab8cf25"> |

- DOM 구조가 변경되면서 shrink 되는 현상도 관측됩니다. 
- 라이브러리에서 대응할지, 애플리케이션에서 대응할지 확인해봐야합니다.

### Version of bezier-react

2.0.0-alpha.12

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by yangwooseong** [comment]
어플리케이션에서 레거시 셀렉트 컴포넌트에서 런타임에 onClick을 주입하고 있어서 생긴 문제입니다
