### ISSUE TITLE
TextField's style is different than before

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#2008]
### Summary

TextField's style is different than before

### Reproduction process

| AS-IS | TO-BE |
|--------|--------|
| <img width="311" alt="image" src="https://github.com/channel-io/bezier-react/assets/58209009/3a93539c-32fe-435c-ab48-271421ee7e16"> | <img width="339" alt="image" src="https://github.com/channel-io/bezier-react/assets/58209009/ece4f4be-b9a4-4c01-b00b-e863763b909e"> |
| <img width="306" alt="image" src="https://github.com/channel-io/bezier-react/assets/58209009/1b535b41-15e5-42fc-a727-f437fd462bd8"> | <img width="314" alt="image" src="https://github.com/channel-io/bezier-react/assets/58209009/39786e03-86aa-41a4-a1c9-24b6fca63b6d"> | 

`AS-IS` 가 현재 버전입니다. `TO-BE` 처럼 동작해야합니다. 3가지의 차이점을 찾아볼 수 있습니다.

1. overflow-x 에 스크롤이 존재함. overflow-x: auto로 스타일은 동일함
2. padding이 존재함
3. 태그가 들어갔을 때 shrink됨

### Version of bezier-react

2.0.0-alpha.12

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by yangwooseong** [comment]
2,3 번째 이슈는 어플리케이션의 마이그레이션 과정에서 생긴 버그였습니다
