### ISSUE TITLE
Public the Bezier Design System on Figma

### ISSUE THREAD

**Issue by amazingnerd** [channel-io/bezier-react#2051]
### Description

Hi, 
It would be awesome if you public the Bezier design system on Figma for us to easy using this github repo. Thanks!

### Reasons for suggestion

Proficiency using this repo

### Proposed solution

Public the Bezier design system on Figma

**Comment by sungik-choi** [comment]
Thank you for your interest in our library. We're not ready to make the design publicly available yet, so I don't think we can do that anytime soon, but we'll let you know when we have a plan.
