### ISSUE TITLE
Explore Storybook 8

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#2080]
### Description

Explore [Storybook 8](https://storybook.js.org/blog/storybook-8/)

### Reasons for suggestion

- 스토리북에 내장된 [Visual test](https://storybook.js.org/docs/writing-tests/visual-testing?ref=storybookblog.ghost.io#install-the-addon)가 매력적인 피쳐로 보이는데, Chromatic의 사용량을 공유하는 기능일 수도 있어 확인이 필요함
- https://github.com/channel-io/bezier-react/pull/1997#issuecomment-1964040154 : react-docgen 문제를 해결하고 넘어가야하고, 해결된다면 syncpack의 버전 제한 설정도 제거해야함

### Proposed solution

생략

### References

- https://storybook.js.org/blog/storybook-8/
- https://storybook.js.org/docs/writing-tests/visual-testing?ref=storybookblog.ghost.io#install-the-addon

**Comment by yangwooseong** [comment]
> Thank you for helping us stress-test the addon! Now that the beta period has ended, snapshots from Visual Tests addon will be tracked in your Chromatic snapshot usage. Learn more about [Chromatic’s pricing tiers](https://www.chromatic.com/pricing?ref=chromaticblog.ghost.io), or [please contact our support team if you have any questions](mailto:support@chromatic.com).

addon의 스냅샷이 크로마틱 스냅샷 사용량에 포함되기 때문에 유효하게 사용하려면 https://github.com/channel-io/bezier-react/issues/1000를 먼저 해결해야할 것 같네요 (참고: https://www.chromatic.com/blog/visual-tests-addon/)
