### ISSUE TITLE
Explore Knip and remove ts-prune

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#2092]
### Description

Explore [Knip](https://knip.dev/) and remove ts-prune

### Reasons for suggestion

> 🚨 ts-prune is going into maintanence mode
> Please use [knip](https://github.com/webpro/knip) which carries on the spirit.
> (https://github.com/nadeesha/ts-prune)

ts-prune 메인테이너가 더 이상 개발되지 않고, knip을 대신 사용하라고 합니다.

### Proposed solution

knip 라이브러리 적용이 가능한지 테스트해보고, 가능하다면 마이그레이션합니다.

**Comment by yangwooseong** [comment]
knip으로 테스트를 해봤으나 ts-prune과 동작을 맞추기가 어려워서 ts-prune에 큰 문제가 생기지 않는 이상 마이그레이션하지 않는 것으로 결정
