### ISSUE TITLE
Remove fixed width of right item in `TextField` component

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#2280]
### Summary

`TextField` 컴포넌트의 `RightItem`에 있는 고정된 width 를 제거합니다. 

### Reproduction process

아래 이미지와 같이 컨텐츠가 길어질 때 끊겨서 보이는 문제가 발생합니다. 사용처에서 white-space:nowrap같은 속성을 넣어야되는 번거로움이 생기기 때문에 디자이너와 합의하여 고정된 width 를 제거하면 좋겠습니다.

![image](https://github.com/channel-io/bezier-react/assets/28595102/b3d5e02d-5de3-41aa-8636-4cb439e488bd)

### Version of bezier-react

2.0.7

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hamza-malik003** [comment]
Kindly assign me this issue. @yangwooseong
