### ISSUE TITLE
`value` option of `Slider` component does not work in storybook 

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#2312]
### Summary

슬라이더 컴포넌트의 스토리북에서 value 값을 조절할 수 없습니다.

### Reproduction process

https://main--62bead1508281287d3c94d25.chromatic.com/?path=/docs/components-slider--docs 

value 를 조절할 수 없습니다. 

### Version of bezier-react

2.0.9

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by nayounsang** [comment]
이 이슈가 아직 해결 안된 것 같아서요. 이 이슈도 제가 시도해봐도 될까요??

**Comment by yangwooseong** [comment]
@nayounsang 넵 감사합니다!
