### ISSUE TITLE
Modify `Button` component not to alter text color when hovered

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#2364]
### Summary

디자인 스펙에 맞지 않는 `Button` 컴포넌트 스타일링을 수정합니다. 

### Reproduction process

현재는 Button 스타일이 tertiary 일 때 호버하면 텍스트 색깔이 바뀌지만 디자인 스펙상으로는 바뀌지 않아야 합니다. 

https://main--62bead1508281287d3c94d25.chromatic.com/?path=/story/components-button--primary&args=styleVariant:tertiary

### Version of bezier-react

2.2.2

### Operating system

- [X] macOS
- [x] Windows
- [x] Linux

### Additonal Information

- [디자인 스펙(internal)](https://www.figma.com/design/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1930-25846&t=xZAWRhLwFAuD8hYu-4)

**Comment by theaniketnegi** [comment]
So, the color of the text is not supposed to change on hover for the tertiary button, right? Or did I interpret it wrong?

**Comment by yangwooseong** [comment]
Yes, color of the text should not change when hovered.
