### ISSUE TITLE
Resolve deprecate warning in sass 

### ISSUE THREAD

**Issue by yangwooseong** [channel-io/bezier-react#2537]
### Description

sass 에서 deprecated 된 문법을 쓰고 있어서 bezier-react 을 빌드할 때 워닝이 뜹니다. 

```
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
```

### Reasons for suggestion

빌드 로그를 깔끔하게 하기 위해 마이그레이션을 하면 좋겠습니다. 

### Proposed solution

https://sass-lang.com/documentation/breaking-changes/import/ 를 참고해서 적절히 마이그레이션 해주세요.

**Comment by sungik-choi** [comment]
rollup-plugin-postcss 이슈: https://github.com/egoist/rollup-plugin-postcss/issues/463
