### ISSUE TITLE
showContentHeader, CoverableHeader 가 복수개 있을 수 있도록 변경

### ISSUE THREAD

**Issue by jwoo0122** [channel-io/bezier-react#325]
## 현재 상황
showContentHeader 상태는 오직 하나임.
## 문제점
화면에 복수개의 Header 가 표시되어도 이들의 표시여부 상태는 하나로 공유되고 있음. 그래서 이 중 하나의 헤더만 unmount 되어도 나머지 header 까지 모두 사라져버림.
## 어떻게 개선할 수 있는지
제안들
1. showHeader 가 단순한 boolean 이 아니라 일종의 id 를 들고 있게 하여, 이들 각각을 관리하고 그 어떤 Header 도 표시할 것이 없을 때 Header 영역을 감추는 방식
# Reference
https://desk.channel.io/root/groups/Front-18500/60706786537f0140bfd2

**Comment by aooen** [comment]
sideView 내부의 children은 useHeader를 가지고 있으면 안되는데, 사용처에서 이렇게 잘못 사용하고 있는 것이 문제입니다. (https://github.com/channel-io/ch-desk-web/pull/7440/commits/21484892d3afe40347832fd0e90c76f88e14a66b 와 같이 MainView에서 올때만 useHeader를 사용하도록 수정되어야 합니다. 현재는 desk 프로젝트에서 관련 부분이 모두 해결되어, 해당 이슈로 인한 문제가 발생하지 않습니다.)
그래서 이 이슈를 해결할 필요는 없다고 생각되어, #550 에서 같이 처리하지 않았습니다.
