### ISSUE TITLE
Main overflow scroll 삭제

### ISSUE THREAD

**Issue by aooen** [channel-io/bezier-react#355]
# 현재상황
![image](https://user-images.githubusercontent.com/33291896/116255556-4ee8ea00-a7ad-11eb-8362-51a82b0dd24c.png)

https://github.com/channel-io/design-system/blob/0439d8d753f6dddcde0295e2dd938f532fb5a83d/src/layout/Main/Main.styled.ts#L23-L24
해당 코드로 인해 항상 스크린샷과 같이 Main 영역 하단에 빈 스크롤바가 표시됨.

## 재현 방법
Windows에서 테스트, 또는 macOS에서 `스크롤 막대 보기: 항상` 설정

## 기대한 동작
https://github.com/channel-io/design-system/pull/229#discussion_r576099222
화면 width가 적을 때 가로 스크롤이 되는 것을 기대한 것으로 보임

## 실제 동작
항상 의미없는 empty 스크롤바가 나오고 있음.

# Reference

**Comment by jwoo0122** [comment]
scroll 삭제를 넘어서 근본적으로 화면 너비가 부족할 때 레이아웃 간의 동작을 수정해야 합니다.
