### ISSUE TITLE
Enhancement `Icon`'s accessibility

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#369]
## 현재 상황

<img width="475" alt="스크린샷 2021-05-07 오후 3 26 51" src="https://user-images.githubusercontent.com/58209009/117406886-b1c64800-af48-11eb-9a84-ca76dea737a9.png">

## 문제점

위와 같음.

## 어떻게 개선할 수 있는지

Icon이 버튼으로 사용되는지, 단순한 장식요소로 사용되는지 구별하여 aria 속성과 focusable, tabIndex 속성 등을 부여해주면 해결할 수 있을 거 같음.

# Reference

- https://css-tricks.com/accessible-svg-icons/
- https://a11y.gitbook.io/graphics-aria/svg-graphics/svg-a11y
- https://developer.mozilla.org/ko/docs/Web/Accessibility/Understanding_WCAG/Keyboard#focusable_elements_should_have_interactive_semantics
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names

**Comment by quino0627** [comment]
오 익스텐션을 사용중이신건가요? @sungik-choi

**Comment by sungik-choi** [comment]
> 오 웹접근성 지표를 보여주는 익스텐션을 사용중이신건가요? @sungik-choi 

파이어폭스 개발자도구에서 확인할 수 있어요.

**Comment by sungik-choi** [comment]
개별 아이콘 컴포넌트에 `aria-label` 을 추가하고, 아이콘 외부에서도 해당 속성값을 사용할 수 있도록하면 좋겠습니다(related to #713).
아이콘 generate시에 작업해주면 될 듯.

```html
<svg aria-label="all" class="..." />
```

```tsx
import { AllIcon } from '...'

console.log(AllIcon.name) // 'all'
```
