### ISSUE TITLE
툴팁 여백 삭제, 글씨 사이즈, word-wrap 조절

### ISSUE THREAD

**Issue by aooen** [channel-io/bezier-react#577]
![image](https://user-images.githubusercontent.com/33291896/129996552-bc67747c-e8a4-4346-838a-49244637ab16.png)

https://desk.channel.io/root/groups/Bezier-62019/611b8288d420a4260b87

+ 영어 word-wrap도 단어 기준으로 수정되는게 맞다 함

**Comment by sungik-choi** [comment]
이 스타일이 라이브러리의 책임이 맞는지 고민이네요. 채널 데스크에서 글로벌 스타일로 처리하는 게 나아보입니다.
