### ISSUE TITLE
Icon Tree Shaking

### ISSUE THREAD

**Issue by quino0627** [channel-io/bezier-react#599]
## 현재 상황
Icon은 as prop을 통해서 각 상황에 맞는 컴포넌트를 렌더링하고 있음
즉 동적으로 컴포넌트가 결정되기 때문에 Tree Shaking이 안됨
Icon을 하나라도 쓰면 모든 Icon이 번들에 포함되기 때문에 이를 해결해야함

## 어떻게 개선할 수 있는지
1. `<Chevron />` 과 같이 각 컴포넌트화된 아이콘을 모두 개별 import
2. Lazy Import (초기 경험이 좋지 않음)

# Reference

**Comment by sungik-choi** [comment]
Fixed by #729
