### ISSUE TITLE
ActivableElement 타입 엔트리 추가

### ISSUE THREAD

**Issue by npbg** [channel-io/bezier-react#604]
## 현재 상황

```typescript
interface ActivableElement {
  activeClassName?: string
  active?: boolean
  allowActive?: boolean
}
```

위 인터페이스가 엔트리에 포함되어있지 않습니다.

## 문제점

active prop 을 쓸 수 있는 디자인시스템 사용처에서 충분히 범용적으로 사용할만한 타입인데 엔트리에 포함되어있지 않아  각 프로젝트 내에서 똑같은 인터페이스를 따로 선언을 해 사용하고 있습니다.

## 어떻게 개선할 수 있는지

해당 인터페이스를 엔트리에 추가합니다.

**Comment by sungik-choi** [comment]
수정되어 이슈 클로즈 하겠습니다!
