### ISSUE TITLE
Text 컴포넌트에 as prop을 잘 활용할 수 있게 변경 필요

### ISSUE THREAD

**Issue by quino0627** [channel-io/bezier-react#607]
## 현재 상황
Text는 기본적으로 span 태그를 활용하고 있으나 Semantic Web을 구성하기 위해서는 상황에 맞는 태그로 변환해주기 위해 as prop을 활용해주어야 함. 현재는 as prop type 불일치로 사용이 어려움
## 어떻게 개선할 수 있는지

# Reference

**Comment by npbg** [comment]
forwardedAs prop 으로 escape 할 수는 있습니다.

**Comment by sungik-choi** [comment]
#620 같은 방식으로 풀 수도 있을 거 같습니다.

**Comment by sungik-choi** [comment]
#906 에서 다룹니다.
