### ISSUE TITLE
Text 등 onClick 등 html element 이벤트 핸들러 타입 강화

### ISSUE THREAD

**Issue by npbg** [channel-io/bezier-react#615]
## 현재 상황

onClick 에 타입이 () => void 로 되어있습니다.

<img width="308" alt="스크린샷 2021-11-22 오후 10 05 22" src="https://user-images.githubusercontent.com/24905674/142969220-e0e77620-9a19-4f03-af9a-733ff04c0843.png">

## 문제점

html element 이벤트 핸들러에서 event 를 기반으로 한 핸들러 작성이 어렵습니다.
대표적인 예시로 event.stopPropagation() 을 쓰기가 어려워 빈 div 로 한번 감싸야합니다.

## 어떻게 개선할 수 있는지

이벤트핸들러 타입의 인자부분에 event 를 optional 로 추가해야할 것 같습니다.

# Reference

**Comment by sungik-choi** [comment]
#648 에서 해결되어 이슈 클로즈하겠습니다!
