### ISSUE TITLE
Avatar를 유저 뿐 아니라 여러 이미지와 그 위에 아이콘을 넣을 수 있도록 확장

### ISSUE THREAD

**Issue by npbg** [channel-io/bezier-react#616]
## 현재 상황

<img width="622" alt="스크린샷 2021-11-24 오후 1 34 57" src="https://user-images.githubusercontent.com/24905674/143175607-b95536f5-52dd-4cf5-b6f0-87e5725aa3d0.png">

<img width="238" alt="스크린샷 2021-11-24 오후 1 36 59" src="https://user-images.githubusercontent.com/24905674/143175753-1bc08777-a7f5-4121-b660-e475756de5ad.png">

Avatar 는 status 라는 prop으로 StatusType 을 받아 Status 값 3개만 분기해서 아이콘 3개만을 보여줄 수 있습니다.

## 문제점

이미지 위에 작은 아이콘이 들어가는 디자인은 유저와 유저의 온/오프라인 상태를 나타낼 때 뿐 외에도 자주 등장할 수 있습니다.
ex. 메신저 플랫폼의 연동 상태를 나타낼 때 메신저 플랫폼의 로고 이미지 + 아이콘 [완료 상태: ✅ / 실패 상태: ✖️ / 펜딩: ⏸] 

## 어떻게 개선할 수 있는지

1. prop 에 status 대신 icon(Name) prop 을 추가하여 원하는 아이콘을 넣을 수 있도록 확장 (breaking change 을 피하기 위해 status 를 남겨두고 iconName 만 추가하는 방법도 있음)
2. Avatar 는 컴포넌트 이름부터 유저용이니까 새로운 이름의 컴포넌트를 하나 새로 추가.

# Reference

**Comment by sungik-choi** [comment]
[Avatar with Custom Status](https://channel-io.github.io/bezier-react/?path=/story/components-avatars-avatar--with-custom-status) 스토리북 한 번 확인해주시겠어요? 현재도 원하는 아이콘을 넣을 수 있는 스펙이 있는데, 다만 어느정도 위치는 정해져있는 상황입니다.

**Comment by npbg** [comment]
> [Avatar with Custom Status](https://channel-io.github.io/bezier-react/?path=/story/components-avatars-avatar--with-custom-status) 스토리북 한 번 확인해주시겠어요? 현재도 원하는 아이콘을 넣을 수 있는 스펙이 있는데, 다만 어느정도 위치는 정해져있는 상황입니다.

아 Avatar 안에 Avatar 를 넣음으로써 가능은 했군요? 감사합니다.
작동은 잘 하는 것 같은데 이 구조가 직관적일지에 대한 의문은 있습니다 !

**Comment by sungik-choi** [comment]
컴포넌트를 만들 때 다른 UI 라이브러리들의 방식을 참고했어요. 

Avatar 안에 children으로 Badge를 넣는 방식을 디폴트로 생각했었고, `status` prop은 children에 들어가는 `Status` 를 `StatusType` enum을 넘기는 거 만으로 쉽게 사용할 수 있도록 하는 방향으로 만들었어요.
