### ISSUE TITLE
[proposal] ButtonSet component

### ISSUE THREAD

**Issue by inhibitor1217** [channel-io/bezier-react#703]
## 현재 상황

<img width="393" alt="스크린샷 2022-01-26 오후 4 50 43" src="https://user-images.githubusercontent.com/25701854/151123569-a168d1a0-62e9-4cc5-b6e0-9018677c8f34.png">

위 스펙 구현하기

## 문제점

현재는 항상 스타일 지정한 div로 구현하게 됩니다.

```tsx
const Buttons = styled.div`
  > * + * {
    margin-left: 6px;
  }
`

...

<Buttons>
  <Button ... />
  <Button ... />
</Buttons>
```

## 어떻게 개선할 수 있는지

위 스펙에 따라 다음과 같은 인터페이스로 만듭니다.

```tsx
interface ButtonSetProps {
  /**
   * @default true
   */
  hasGap?: boolean
}

<ButtonSet> // gap 6px
  <Button ... />
  <Button ... />
</ButtonSet>

<ButtonSet hasGap={false}> // gap 0px
  <Button ... />
  <Button ... />
</ButtonSet>
```

ButtonSet 내에 Button 말고 다른 element가 들어오는 경우는 안티패턴으로 합니다.

# Reference
없음.

**Comment by inhibitor1217** [comment]
Stack 컴포넌트 (#632) 와 함께 생각해봐도 좋을 듯.

**Comment by sungik-choi** [comment]
<img width="801" alt="스크린샷 2022-01-27 오전 11 51 10" src="https://user-images.githubusercontent.com/58209009/151283387-1d378694-888c-43c2-af50-b900272bdc92.png">

위와 같은 방식으로 구현되면 좋지 않을까 싶습니다!

**Comment by Seolhun** [comment]
```tsx
const ButtonGroup = ({ children, spacing }) => {
  if (!children) { return null }

  return (
    <ButtonGroupWrapper>
        {React.Children.map(children, child => (
          React.cloneElement(child, {
            ...child.props,
            spacing,
          })
        ))}
    <ButtonGroupWrapper>
)
};
```

**Comment by sungik-choi** [comment]
<img width="396" alt="스크린샷 2022-02-03 오후 3 30 04" src="https://user-images.githubusercontent.com/58209009/152292613-eb3d0304-e346-47ea-8c99-7a154b5e8d10.png">

2022-02-03 피그마 기준으로 위처럼 스펙이 정의되어있어 spacing은 6으로 고정해도 될 듯.

**Comment by sungik-choi** [comment]
내부적으로 Stack을 통해 구현하면 될 듯.
