### ISSUE TITLE
Re-implement `Switch` component using `Switch` in Radix UI

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#711]
## 현재 상황

현재 `Switch` 컴포넌트는 단순 `div` 엘리먼트로 구현되어있습니다.

## 문제점

의미없는 div 엘리먼트여서 발생하는 문제점들이 있습니다.

1. 시맨틱하지 않습니다.
2. 키보드 접근이 되지 않습니다.
3. 키보드를 통한 조작이 불가합니다.

## 어떻게 개선할 수 있는지

`Switch` 컴포넌트는 형태가 다를 뿐, **하나의 체크박스와 UX가 동일**합니다. 체크박스를 커스텀 스타일링한 방식으로 구현을 변경해야합니다. 

### 업데이트 (2022.11.09)

- https://www.radix-ui.com/docs/primitives/components/switch#switch 을 참고하여 구현합니다.
- https://github.com/channel-io/bezier-react/issues/983 을 참고하여 mdx, JSDoc을 작성합니다.

# Reference

- https://chakra-ui.com/docs/form/switch
- https://mui.com/components/switches/#main-content

**Comment by Dogdriip** [comment]
참고: https://www.w3schools.com/howto/howto_css_switch.asp
