### ISSUE TITLE
MainViewHeaderBar를 Bezier으로 이전

### ISSUE THREAD

**Issue by quino0627** [channel-io/bezier-react#720]
## 현재 상황
현재 데스크에서 사용중인 MainViewHeaderBar는 Layout에서 Header 영역의 전반적인 UI를 담당하는 컴포넌트임.
Bezier의 Layout/Header 컴포넌트와 어느정도 유사성이 존재함.

## 문제점
Bezier 컴포넌트로 이를 귀속시켜서 여기서 사용하는 일부 로직과 스타일링 코드를 일원화해야 함.
- Header height는 70px이고, 상황에 따라 84px인 경우도 있는 것으로 아는데 디자인팀과 이부분을 합의하는 과정이 필요함
- SupportBotEditor등에 존재하는 Header는 다른 특성을 가지고 있는데 이부분은 독립적으로 가는지도 확인이 필요함

## 어떻게 개선할 수 있는지

# Reference

**Comment by sungik-choi** [comment]
데스크 어플리케이션 내부에서 구현 예정.
