### ISSUE TITLE
Change `GNB` Component Implementation to nav element

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#726]
## 현재 상황

현재 `div` 엘리먼트로 구현되어 있습니다.

## 문제점

브라우저, 검색엔진이 글로벌 네비게이션인지 알 수 없습니다.

## 어떻게 개선할 수 있는지

HTML5의 시맨틱 태그 중 `nav` 태그를 사용하여 의미를 부여할 수 있습니다.

# Reference

https://developer.mozilla.org/ko/docs/Web/HTML/Element/nav

**Comment by carlos-channel-io** [comment]
지금은 못 하겠지만, 컨콜 할때 GNB를 손댈 것 같아서 제가 챙겨보겠습니다.
