### ISSUE TITLE
Elevation theme always references BezierProvider's Foundation value

### ISSUE THREAD

**Issue by guswnsxodlf** [channel-io/bezier-react#740]
## 기대한 동작
`LightFoundation.ev2()`을 사용하면 밝은 테마의 색상만 나와야 함

## 실제 동작
스타일에 `LightFoundation.ev2()` 이런 식으로 light로 강제한 스타일을 주어도 설정한 테마 색상으로 스타일이 나옴.

# Detail
![Screenshot 2022-03-10 at 15 37 29](https://user-images.githubusercontent.com/14245930/157872795-2432b864-a93b-4ac1-b59d-5241cdaca47b.png)
Elevation이 Light/Dark Foundation에 분기되지 않고 같은 값이 들어가기 때문인듯

**Comment by sungik-choi** [comment]
v2에서 기존 `ev` 제거 및 CSS Variable을 참조하는 방식으로 수정하면 해결될 예정
