### ISSUE TITLE
BezierProvider의 sass 대응용 ThemeVar가 전역에 적용됨

### ISSUE THREAD

**Issue by guswnsxodlf** [channel-io/bezier-react#742]
# 현재상황
## 재현 방법
한 페이지에서 하나의 컴포넌트에 BezierProvider를 사용하여 그 자손들에게 DarkFoundation을 주입시키면, 그 페이지 전체에서 scss를 사용하는 컴포넌트의 색상 값이 DarkFoundation 전용 색상으로 바뀝니다.

LightFoundation의 경우도 동일한 버그가 있음

## 기대한 동작
해당 컴포넌트 내부에서만 scss 색상값을 주입하도록 하여 그 외부에는 영향이 가지 않도록 하여야 합니다.

---

# 해결 방법
아래에 버그를 수정하는 방법들 중 몇 가지를 설명합니다. 

## Method 1
SCSS theme vars를 주입할 Scope를 `BezierProvider` -> `ThemeVars`의 prop으로 넘겨줍니다. 
`ThemeVars`는 해당 prop이 있으면 그 scope 안에, 아니면 `:root`에 SCSS theme vars를 주입합니다.

### Cons
[Component selector](https://styled-components.com/docs/advanced#referring-to-other-components)로 치환되지 않는 컴포넌트 (예: forwardRef 등으로 감싼 컴포넌트) 등은 scope로 주입이 불가능합니다.

## Method 2
- `BezierProvider`에서 div wrapper를 만들어 언제나 해당 wrapper에 SCSS theme vars를 주입합니다.

### Cons
- Provider가 react component에 데이터를 공급하는 역할을 너머 실제 HTML을 추가하게 됩니다. (div wrapper)
- 채널 데스크 마이그레이션 이슈가 있습니다.

**Comment by sungik-choi** [comment]
Ref: https://chakra-ui.com/docs/styled-system/recipes/page-specific-color-mode
