### ISSUE TITLE
Tag, Badge 에 children prop를 Button의 text prop과 같은 형태로 개선

### ISSUE THREAD

**Issue by choichoigang** [channel-io/bezier-react#755]
## 현재 상황
`Tag`, `Badge`는 children prop를 통해서 text를 렌더링하고 있음
## 문제점
실제로 `Tag`, `Badge`는 내부적으로 `children`를 `TagBadgeText`에 렌더링 하고 있으며 이는 `Tag`, `Badge`에 들어가는 content는 text만 가능하다 라는 말과 같습니다. **(이게 기획이 아니라면 컴포넌트 네이밍을 변경해서 명확하게 하는 방향으로 개선..?)**
## 어떻게 개선할 수 있는지
`Button` 컴포넌트와 같이 text prop으로 받도록 변경

# Reference

**Comment by inhibitor1217** [comment]
+) 가이드 문서를 보면 `content`는 보통 (string 등으로) 타입이 restricted 된 prop을, `children`은 일반적인 `ReactNode` 타입 prop을 의미하는 것 같습니다. 그래서 `Tag`, `Badge` 에 text content만 들어갈 수 있다면 `string` 타입의 `content` prop으로 지정하면 좋을 듯 합니다.

![스크린샷 2022-04-19 오전 11 55 20](https://user-images.githubusercontent.com/25701854/163911042-3c21657a-691c-408f-8406-4a3faf01a01f.png)

오히려 `Button`이 가이드를 따라가도록 조정해야 하는 부분이긴 합니다 😅

**Comment by sungik-choi** [comment]
저도 @inhibitor1217 말씀에 동의합니다.
개인적인 취향으론, `Button` 도 `children` prop을 사용하도록 변경되었으면 좋겠네요.

```html
<button>버튼</button>
```

이런 마크업 방식이 자연스러운 거 같다고 생각해서요.

**Comment by sungik-choi** [comment]
따로 진척이 있는 거 같지 않아 이 이슈는 Close하겠습니다.
