### ISSUE TITLE
베지어 릴리즈 시 릴리즈방에 메시지가 안 옴

### ISSUE THREAD

**Issue by quino0627** [channel-io/bezier-react#767]
https://desk.channel.io/root/threads/groups/Bezier-62019/62452b5800a4a704f404/62452b5800a4a704f404

**Comment by sungik-choi** [comment]
이슈 템플릿 안쓰고도 이슈 오픈 가능한가요?

**Comment by quino0627** [comment]
일단 깃헙 봇 재등록 프로세스 진행함 ! 결과 보고 close

**Comment by quino0627** [comment]
https://github.com/channel-io/ch-inhouse/issues/441 로 이전
