### ISSUE TITLE
KeyValueListItem 디자인 변경

### ISSUE THREAD

**Issue by CHEWCHEWW** [channel-io/bezier-react#775]
### 요약

KeyValueListItem의 왼쪽 key 너비를 동일하게 변경합니다.

![April 18th 2022, 8_46_13 pm](https://user-images.githubusercontent.com/60692645/166395664-acee94a1-0fab-4155-a0af-16902aa8e741.png)

### 제안 이유

디자인 시스템 스펙 변동에 따라 베지어 디자인 시스템 스펙을 변경합니다.

### 개선 방안

key의 너비를 통일합니다.

### 레퍼런스

https://desk.channel.io/root/threads/groups/Bezier-62019/625d4fbf9b8131c5b504/625d4fbf9b8131c5b504

**Comment by sungik-choi** [comment]
👍 need triage 뱃지는 지워주셔도 됩니다! 분류용 라벨이에요

**Comment by CHEWCHEWW** [comment]
> sungik

지웠다고 생각했는데 남아있네요 🤔

**Comment by CHEWCHEWW** [comment]
> 👍 need triage 뱃지는 지워주셔도 됩니다! 미분류 표시용 라벨이에요

지웠다고 생각했는데 남아있네요 🤔
