### ISSUE TITLE
beizer Badge PR 마무리하기

### ISSUE THREAD

**Issue by choichoigang** [channel-io/bezier-react#776]

**Comment by sungik-choi** [comment]
@quino0627 프로젝트 사용하면서 이런 이슈들을 관리하기 애매하네요. 

- 오픈소스 라이브러리의 이슈에 개인 일정 관리용 태스크가 들어가는 게 맞을지
- 이슈 템플릿을 무시하고 이슈가 작성되는 게 걸림

**Comment by quino0627** [comment]
@sungik-choi (fyi. @choichoigang , @CHEWCHEWW )
1번과 관련하여 이런 형태의 이슈는 지양해야 하는게 맞다고 생각합니다
툴 도입 이전에 진행하던 티켓을 어떻게 추가할 것인지에 대한 혼란이 있는 거라고 판단했어요
또한 이 이유는 프로젝트 매니징 툴의 도입이 가장 어려운 이유 중 하나라고 생각해요.
오픈소스 라이브러리 이슈에는 해당 오픈소스를 위한 태스크가 들어가야 하는것이 맞습니다
따라서 이 이슈는 **기존에 있던 PR을 프로젝트 보드에 추가하는게 맞는 방식이라고 생각합니다** (PR이 올라오지 않았다면 이슈부터 생성하고, 그 이슈를 링킹하면 되겠습니다)

2번의 경우에는 빠르게 해결할 수 있습니다
각 레포에서 이슈를 생성함과 동시에 Project에 추가하는 것입니다.
저는 프로젝트에서 issue로 컨버팅하는게 편할 것이라 생각했었는데 - 프로젝트만 보고 태스크를 추가/삭제 할 수 있으니까요 - 템플릿을 쓰는 경우에는 기존의 rule을 어기는 것이므로 이렇게 하면 안될 것 같습니다

**Comment by choichoigang** [comment]
project에서 생성된 row가 이런식으로 생성될 수 있다는 점을 간과한 것 같습니다.
앞으론 task를 추가하는 프로세스를 각 레포에서 생성 후 -> 등록하는 형태로 변경하도록 하겠습니다!
(해당 issue는 close 하도록 하겠습니다 🙇‍♂️)

@quino0627 @sungik-choi @CHEWCHEWW
