### ISSUE TITLE
Tooltip is highly likely to not call onHide on certain components

### ISSUE THREAD

**Issue by Seolhun** [channel-io/bezier-react#829]
### 요약

툴팁이 매우높은 확률로 onHide가 되지 않음

> 원인은 차후에 더 파악해보겠습니다. setTimeout과 연관되어보입니다.

### 재현 과정

https://user-images.githubusercontent.com/16330024/174573037-f929cdd6-7c73-4393-a99c-24ba7a93ef31.mov

- 버튼을 벗어나면 onHide가 호출되어야하는데 그렇지 않음
- Switch에서는 잘 동작함.
- Tooltip children이 아닌, Tooltip 자체를 지나가면 onHide가 잘 동작함

### bezier-react 버전

^1.0.0-next-v1.141

### 운영체제

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by sungik-choi** [comment]
#979
