### ISSUE TITLE
semantic-release가 모든 commit type에 대해서 release를 수행하도록 변경

### ISSUE THREAD

**Issue by quino0627** [channel-io/bezier-react#832]
### 요약

현재는 특정한 커밋 타입 (fix, feat, chore 등)이 머지될때만 release가 수행되고 있음.
모든 커밋 타입에 대해서 release가 수행되게 변경하는 것을 제안합니다.

### 제안 이유

style 타입의 커밋이 릴리즈되지 않는 것을 원인으로 합니다.
또한 docs 역시 바로 storybook deploy와 연계되어야 하기 때문에, 사실 대부분의 커밋은 즉시 릴리즈가 되면 좋습니다.

릴리즈가 바로 되면 문제 없지만,
릴리즈가 밀리면 문제되는 경우가 발생하기 때문에 제안합니다.

### 개선 방안

semantic release 옵션 오버라이드로 가능한 것으로 파악한 바 있음.

**Comment by sungik-choi** [comment]
https://stackoverflow.com/questions/64288287/how-to-make-semantic-release-do-a-release-on-a-docs-commit

**Comment by aooen** [comment]
style은 코드 스타일 수정(컨벤션 맞추고 등등)이라서 릴리즈를 수행해야 될 필요가 없는데 css style을 바꾸는 커밋에 대해서 그렇게 표시해주고 있다면 잘못 하고 있는 것 같습니다.

**Comment by sungik-choi** [comment]
네 커밋 타입이 style인데 내용을 변경하고 있다면 커밋을 잘못하고 있는 게 맞다고 생각합니다. docs 정도는 고려해볼만한듯해요
