### ISSUE TITLE
Enhance the `bezier-figma-plugin`

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#863]
### 요약

`bezier-figma-plugin` 의 아이콘 추출 기능 및 그에 관련된 워크플로우가 강화되어야 합니다.

### 제안 이유

디자인 팀 피드백 및 changesets 도입으로 인한 요구사항 추가 반영

### 디자인 팀 피드백

- 변경된 아이콘만 업데이트하는게 좋겠다는 피드백. 현재 구현으론 아이콘 저장 경로에 해당하는 모든 아이콘을 덮어 씌우는 방식으로 구현되어 있습니다. 
- 아이콘의 양이 상당하여 Git blob을 생성하는데 상당한 시간이 소요됩니다. 

Git blob 생성 시간을 획기적으로 단축하면 첫번째 피드백을 자연스럽게 해결할 수 있지 않을까합니다. 혹은 현재 아이콘 저장 경로를 덮어 씌우지 않고 추가만 하는 방식을 추가할 수도 있을 거 같습니다.

### 워크플로우 추가

- #855 에서 changeset이 추가되면서, 자동으로 릴리즈 노트를 생성하지 않습니다. 
- ~~(예시) PR 설정에 `new:icon` 라벨을 추가하고, 해당 라벨을 가진 PR이 오픈되면 체크아웃 후 changeset을 실행, 커밋 후 푸시하는 워크플로우가 추가되어야 합니다.~~
  - #1328 에서 자동으로 라벨을 추가하는 기능을 추가했습니다.
    - 구현하다보니 특정 라벨을 '추가한 상태로' PR(issue)를 오픈할 수는 없었습니다. 오픈 후 라벨을 추가하는 방식으로 동작하기 때문에 그에 맞는 적절한 액션 트리거를 설정해야 합니다.
    - 잘못 라벨을 추가했을 때, 액션이 트리거되지 않도록 / 라벨을 추가했다 제거했다 할 경우 액션이 계속해서 실행되지 않도록 구현해야합니다.
- ~~`build:icon` 커맨드를 위 워크플로우에서 함께 실행하고, 실제 빌드시에는 아이콘 빌드는 실행하지 않도록 하면 좋을 거 같습니다.~~ `bezier-icons` 패키지 추가로 해결됨

### 기타

- ~~PR에 assignee가 자동으로 추가되도록~~ : 가능은 하나 불필요하다고 판단 (#1328)
- ~~PR 제목을 conventional commit에 맞도록 변경하는 게 좋을 거 같습니다. (`feat(icons): update the icons`)~~
- PR Description에 테이블로 변경/추가/삭제 된 아이콘이 잘 정리되어서 보여지면 좋을 거 같습니다.

### 레퍼런스

- https://github.com/generates/changeset-action

**Comment by sungik-choi** [comment]
This Pull Request was generated by bezier-figma-plugin.

위 PR 설명에서 `bezier-figma-plugin` 링크를 패키지 경로로 연결시키면 좋을 듯.

**Comment by sungik-choi** [comment]
@yangwooseong [베지어 아이콘 관리](https://www.notion.so/channelio/54a12727879c4e8c9978e5946bccb3d5?pvs=4) 문서도 최신화되면 좋을 거 같아요. 아래 변경사항들이 적용되면 좋을 거 같습니다~

- 문서를 Bezier Design System 하위로 이동하고, 해당 페이지에는 페이지 링크 걸기
- 피그마 플러그인을 로컬로 다운받지 않아도 됨. 사내 플러그인으로 원격 다운로드가 가능함
- 동작이 변경된다면 문서에 반영하기, 혹은 문서를 GitHub README에 잘 작성하고, 노션은 GitHub README에 링크만 거는 방식으로 변경

**Comment by yangwooseong** [comment]
넵 확인해볼게요!

**Comment by sungik-choi** [comment]
- 아마 아시겠지만 플러그인이 업데이트되면 피그마에 아티팩트를 업로드하고, 릴리즈 노트를 작성해야해요.
- 개발 과정에 대한 내용들을 정리해서, '피그마 플러그인 개발 가이드'같은 이름으로 저희 위키에 문서를 추가해주셔도 좋을 거 같습니다..!
