### ISSUE TITLE
[WIP] Separate Bezier colors into separate package

### ISSUE THREAD

**Issue by Dogdriip** [channel-io/bezier-react#968]
### Description

WIP

### Reasons for suggestion

WIP

### Proposed solution

WIP

### References

- [@radix-ui/colors](https://github.com/radix-ui/colors)
- [Material Design 3 - Design tokens](https://m3.material.io/foundations/design-tokens/overview)

**Comment by sungik-choi** [comment]
색상값을 모두 포함한 bezier-token 패키지로 분리할 예정입니다.
