### ISSUE TITLE
Re-implement `Modal`, `ConfirmModal` component using `Dialog`, `AlertDialog` in Radix UI

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#978]
### Description

`Modal` 컴포넌트를 Radix UI의 `Dialog`, `AlertDialog` 컴포넌트를 사용하여 재구현합니다.

### Reasons for suggestion

- 접근성, 키보드 인터랙션 및 포커스 트랩 등 현재 모달 구현에서 지원하고 있지 않은 기능들을 추가
- z-index를 명시적으로 지정하지 않아도 마운트된 순서대로 모달이 쌓여 보여질 수 있도록 개선

### Proposed solution

- #983 을 참고하여 mdx와 JSDoc을 추가합니다.

### References

- https://www.radix-ui.com/docs/primitives/components/dialog
- https://www.radix-ui.com/docs/primitives/components/alert-dialog

**Comment by quino0627** [comment]
Modal 변경하실 때 ModalContent.description의 type이 string -> ReactNode로 변경되어야 할 필요성이 있어서, 같이 챙겨주시면 어떨까 해요.
description에 string이 아닌 <br/> 등이 포함되는 경우에 사용하기가 어려워요

**Comment by sungik-choi** [comment]
2분할된 형태의 모달, 3분할된 형태의 모달의 경우 어떻게 구현할지 고민 필요.
