### ISSUE TITLE
Re-implement `Tooltip` component using `Tooltip` in Radix UI

### ISSUE THREAD

**Issue by sungik-choi** [channel-io/bezier-react#979]
### Description

Tooltip 컴포넌트를 Radix UI의 Tooltip 컴포넌트를 사용하여 재구현합니다.

### Reasons for suggestion

- 툴팁 컴포넌트를 라이브러리 없이 직접 구현하면서 각종 버그들이 발생하고, 완성도가 떨어지는 면이 있습니다. 잘 만들어진 라이브러리를 통해 재구현하면서 기존의 많은 버그들을 수정할 수 있을 거라 기대합니다.

### 요구사항

1. 키보드 인터랙션 지원: 포커스 됐을 경우에도 툴팁이 나타나도록
  - 포커스 시 `Esc` 키를 누르면 툴팁이 사라져야 합니다.  
2. 그 외 현재 `Tooltip` 의 기능 (delay, hover 등)

### Proposed solution

- #577 을 함께 수정하고 Close 합니다.
- #983 을 참고하여 mdx와 JSDoc을 추가합니다.

### References

- https://www.radix-ui.com/docs/primitives/components/tooltip

**Comment by sungik-choi** [comment]
- 현재 툴팁 컴포넌트엔 큰 문제는 없어서, 트레이드오프를 따져봐야함
- 툴팁 안에 링크가 들어가는 케이스에 대해 리서치 필요

**Comment by yangwooseong** [comment]
링크가 들어가는 케이스는 어떤 것이 문제가 될 수 있는 건가요..?

**Comment by sungik-choi** [comment]
> 링크가 들어가는 케이스는 어떤 것이 문제가 될 수 있는 건가요..?

문제가 된다기보다, 링크에 호버를 하는 케이스 등에 대해 리서치가 필요하다는 코멘트였습니다!

**Comment by yangwooseong** [comment]
현재 툴팁이 몇가지 문제점들이 있어 보여서 대체를 하면 좋을 것 같은데, 사용처가 워낙 많다보니(200개 정도) 결정하기 쉽지 않은 면이 있네요. 발견된 이슈만 몇가지 열거하자면..

1. 접근성 문제 - 키보드 접근이 전혀 안되고, 접근성 속성이 전혀 없음
2. 자잘자잘한 버그들 - https://github.com/channel-io/bezier-react/issues/829 라던지, 툴팁이 생겼을 때 빠르게 툴팁으로 마우스를 옮겨서 클릭하면 툴팁 밑에 있는 element 에 onClick 이벤트가 발생한 것과 동일한 효과가 나타남.

https://user-images.githubusercontent.com/28595102/210478051-342e0094-28a3-4eb2-a6cd-7b29e30c4595.mov

3. `<Tooltip> { child } </Tooltip>` -> `<div> { child } </div>` 와 같이 Tooltip 을 적용하는 target element 위에 div 를 생성시키는 문제. 이 div 때문에 의도치 않게 아래처럼 스타일링을 다시 해야하는 경우가 많이 발생하고 있음. 

```typescript
import { Tooltip as BaseTooltip } from '@channel.io/bezier-react'

export const Tooltip = styled(BaseTooltip)`
  display: flex;
  align-items: center;
`

**Comment by sungik-choi** [comment]
> 현재 툴팁이 몇가지 문제점들이 있어 보여서 radix 로 재구현을 하면 좋을 것 같은데, 사용처가 워낙 많다보니(200개 정도) 결정하기 쉽지 않은 면이 있네요. 발견된 이슈만 몇가지 열거하자면..

- 구현 후 로컬 테스트해보시면서, 괜찮다면 `AlphaTooltip` 같은 이름으로 점진적 마이그레이션하는 방식은 어떨까요?
- radix 로 기능 구현의 어디까지 대체 가능한지 궁금하네요 🤔. 저도 아직 리서치를 해보지 않아서... [Floating UI](https://floating-ui.com/)같은 라이브러리를 써야할 수도 있을 거 같구요
- https://github.com/channel-io/bezier-react/issues/1064 도 함께 챙겨보면 좋을 거 같아요

**Comment by yangwooseong** [comment]
현재 베지어 툴팁에서 열어주는 interface 를 보면 radix 로 대체할 때 큰 장애물이 될만한 요소는 없는 것 같네요. prop 별로 나누어서 보면..
- `delayHide` 같은 경우는 radix 에서 지원을 안해주긴 하지만 직접 timer 로 구현해주면 될 것 같아요.
- `placement`는 `TooltipContent` 에서 `useMergedRefs` 훅으로 `TooltipContent`의 ref 와 `Tooltip`의 ref를 머지해서 사용하는 곳의 로직이 아리송해서 현재 계산하는 로직을 그대로 활용할 수 있을지 가늠이 안되는데, `Tooltip`에 ref 를 넘겨주는 곳이 없는 것을 보면 `useMergedRefs` 부분은 아마 무시해도 괜찮을 것 같다는 예상입니다. 
- 그 밖에 `delayShow`, `disabled`, `offset` 등은 radix 에서 지원을 해주고 있고, `lazy` option 은 지금처럼 직접 구현하면 될 것 같네요.
- `className` 관련된 부분도 문제 될 건 없을 것 같고요. 


Floating UI 는 radix 보다 훨씬 다양한 기능을 제공하지만 사용법이 조금 더 복잡해보입니다. `delayHide` 도 지원해주고, `placement` 또한 직접 계산하지 않아도 됩니다. 

저는 radix 로 구현을 진행해보고 해결하기 어려운 문제가 생기면 Floating UI 로 바꾸는 게 좋을 것 같다는 생각이긴 합니다..!

**Comment by sungik-choi** [comment]
- `lazy` 옵션이 꼭 필요한지도 확인해보면 좋을 거 같아요.
- 개인적으론, `placement` 계산 로직도 대체할 수 있다면 대체하는 게 좋지 않을까 싶습니다! 라이브러리에서 충분히 잘 구현해놓았고, common한 동작이라고 생각해서 굳이 새로 구현할 필요가 있을까 싶어요.

**Comment by Dogdriip** [comment]
팀 내에서 공유되었던 Tooltip 관련 레퍼런스들을 참고차 달아둡니다.

- Building a tooltip component: https://web.dev/building-a-tooltip-component/
- Popover API
  - https://developer.chrome.com/docs/web-platform/popover-api/
  - https://zenn.dev/yusukehirao/articles/popover-api-and-attributes
- MUI - Popover: https://mui.com/material-ui/api/popover/
